routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\AdminConfig;
use Carbon\Carbon;

Route::get('/', function () {
    return view('welcome');
});



Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::delete('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/foods', 'FoodController');

Route::resource('/users', 'UserController');

Route::resource('/roles', 'RoleController');

Route::resource('/accesses', 'AccessController');


Route::get('/reserves/create', 'ReserveController@create');
//Route::post('/reserves/{schedule}/store', 'ReserveController@store');
Route::post('/reserves', 'ReserveController@store');
Route::delete('/reserves/{reserve}/destroy', 'ReserveController@destroy');

//Route::get('/schedules', 'ScheduleFoodController@index');
Route::get('/schedules/create', 'ScheduleFoodController@create');
Route::post('/schedules/store', 'ScheduleFoodController@store');
Route::get('/schedules/shownextweek', 'ScheduleFoodController@showSchedulesReservedByUsers');


Route::delete('/schedules/{scheduleFood}/reserve/destroy', 'ScheduleFoodController@deleteReservations');


Route::get('/roles/{role}/permissions', 'PermissionRoleController@create');
Route::post('/roles/{role}/permissions/store', 'PermissionRoleController@store');
Route::delete('/permissionroles/{permissionrole}/destroy', 'PermissionRoleController@destroy');

Route::get('/password/{user}/edit', 'UserController@passwordEdit');
Route::patch('/password/{user}/update', 'UserController@passwordUpdate');

Route::get('/users/{user}/editpassword', 'UserController@editOwnPassword');
Route::patch('/users/{user}/updatepassword', 'UserController@updateOwnPassword');

Route::get('/print', 'ScheduleFoodController@print');

Route::resource('/configs', 'AdminConfigController');


Route::get('/logs', 'LogController@index');


Route::delete('/schedules/{schedule}/users/{user}', 'ScheduleFoodController@deleteUserReserve');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Hekmatinasser\Verta\Verta;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
//    protected $fillable = [
//        'name', 'email', 'password',
//    ];

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function role()
    {
        return $this->belongsTo(\App\Role::class, 'role_id');
    }

    public function reserves()
    {
        return $this->hasMany(Reserve::class, 'user_id');
    }

    public function reserve($schedule)
    {
        if ($reserve = $this->reserves()->where([
            ['user_id', '=', $this->id],
            ['schedule_id', '=', $schedule->id],
        ])->first()) {
            return $reserve;
        }
        return false;
    }

    public function access($table)
    {
        return $this->role->access()->where('table_name', $table)->get();
    }

    public function reserveAvailable(ScheduleFood $schedule)
    {
        $scheduledate = Carbon::parse($schedule->date)->startOfWeek(Carbon::SATURDAY);
        $thisweek = Carbon::now()->startOfWeek(Carbon::SATURDAY);
        $thisweek1 = Carbon::now()->startOfWeek(Carbon::SATURDAY);

        if ($scheduledate->greaterThanOrEqualTo($thisweek->addWeeks(2))){
            return true;
        }elseif ($scheduledate->greaterThanOrEqualTo($thisweek1->addWeek())){
            return !Carbon::now()->startOfWeek(Carbon::SATURDAY)->addDays(AdminConfig::getDay()-1)
                ->addHours(AdminConfig::getHour())->addMinutes(AdminConfig::getMinute())->isPast();
        }else {
            return false;
        }

    }

    public function cancelReserveAvailable(ScheduleFood $schedule)
    {
        $dayOfWeek = $schedule->date->startOfWeek(Carbon::SATURDAY)->dayOfWeek;

        $scheduledate = Carbon::parse($schedule->date)->startOfWeek(Carbon::SATURDAY);
        $thisweek = Carbon::now()->startOfWeek(Carbon::SATURDAY);

        if ($scheduledate->greaterThanOrEqualTo($thisweek->addWeeks(2))){
            return true;
        }elseif ($scheduledate->equalTo($thisweek->addWeek())){
            if (
                Carbon::now()->dayOfWeek == AdminConfig::getDay() &&
                Carbon::parse(Carbon::now()->format('H:i'))->greaterThan(Carbon::parse(AdminConfig::getTime()))
            ){
                return false;
            }else{
                return true;
            }

        }else {
            return false;
        }

    }


    public function reservationsByDate($date)
    {
        return $this->reserves()->join('schedule_foods', 'schedule_id', 'schedule_foods.id')
            ->where('date', '>=', $date)
            ->where('date', '<', $date)
            ->get();
    }

    public static function usersReservedSchedule($date = null)
    {
        $users = ScheduleFood::weeklySchedules($date)->orderBy('date')
            ->join('reserves', 'schedule_foods.id', 'reserves.schedule_id')
            ->join('users', 'reserves.user_id', 'users.id');

        $userids = array_column($users->select('users.id')->distinct()->get()->toArray(), 'id');

        return User::whereIn('id', $userids)->orderBy('lastname')->get();
    }

    public function logs()
    {
        return $this->hasMany(Log::class, 'user_id');
    }

    public function fullName()
    {
        return " " . $this->firstname . " " . $this->lastname . " ";
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Helper\Helper;
use App\Http\Requests\UserRequest;
use App\Log;
use App\Role;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $this->authorizeForUser(auth()->user(), 'viewAny', \App\User::class);
        $users = User::orderBy('employnumber')->orderBy('lastname')->paginate(10);
        return view('users.index', compact('users'));
    }

    public function create()
    {
        $this->authorizeForUser(auth()->user(), 'create', \App\User::class);
        $roles = Role::userRolesToProve(auth()->user());
        return view('users.create', compact('roles'));
    }

    public function store(UserRequest $request)
    {

        $this->authorizeForUser(auth()->user(), 'create', \App\User::class);

        $user = User::create([
            'firstname' => $request->firstname,
            'lastname' => $request->lastname,
            'employnumber' => $request->employnumber,
            'phone' => $request->phone,
            'role_id' => $request->role_id,
            'password' => bcrypt($request->password)
        ]);

        Log::log('users', "ایجاد",' ایجاد کاربر جدید توسط '. auth()->user()->firstname . " " . auth()->user()->lastname);


        session()->flash('success', 'کاربر با موفقیت افزوده شد');

        return redirect(route('users.index'));
    }

    public function edit(User $user)
    {
        $this->authorizeForUser(auth()->user(), 'update', $user);

        $roles = Role::all();
        return view('users.edit', compact('roles', 'user'));
    }

    public function show(User $user)
    {
        $this->authorizeForUser(auth()->user(), 'view', $user);
        $reserves = $user->reserves()->join('schedule_foods', 'reserves.schedule_id', '=', 'schedule_foods.id');
        if(request('startdate') && request('enddate')){
            $startdate = Helper::toGregorian(Carbon::parse(request('startdate')));
            $endtdate = Helper::toGregorian(Carbon::parse(request('enddate')));
            $reserves = $reserves->where('date', '>=', $startdate)
            ->where('date', '<', $endtdate->addDay());
        }
        $reserves = $reserves->orderBy('date')->get();
        return view('users.show', compact('user', 'reserves'));
    }

    public function update(User $user, Request $request)
    {
//        dd($request->all());
        $this->authorizeForUser(auth()->user(), 'update', $user);

        $this->validate($request,[
            'firstname' => ['required', 'min:3'],
            'lastname' => ['required', 'min:3'],
            'employnumber' => 'required',
            'phone' => 'required',
            'role_id' => 'required'
        ],[
            'firstname.required' => 'نام کاربر الزامی‌ است',
            'firstname.min' => 'نام کاربر حداقل باید ٣ کاراکتر باشد',
            'lastname.required' => 'نام خانوادگی کاربر الزامی‌ است',
            'lastname.min' => 'نام خانوادگی کاربر حداقل باید ٣ کاراکتر باشد',
            'employnumber.required' => 'شماره کارمندی الزامی‌ است',
            'phone.required' => 'شماره موبایل الزامی‌ است',
            'role.required' => 'انتخاب نقش الزامی‌ است'
        ]);

        $user->update($request->all());


        Log::log('users',  "ویرایش",' به روز آوری اطلاعات کاربر ' . $user->fullName() . ' توسط ' . auth()->user()->fullName() . ' به شماره کارمندی '.  auth()->user()->employnumber);


        session()->flash('success', 'اطلاعات کاربر با موفقیت ویرایش شد');

        return redirect('/users');
    }

    public function passwordEdit(User $user)
    {
        $this->authorizeForUser(auth()->user(), 'update', $user);
        return view('users.passwordedit', compact('user'));
    }


    public function passwordUpdate(Request $request, User $user)
    {
        $this->authorizeForUser(auth()->user(), 'update', $user);

        $this->validate($request, [
            'password' => 'required|min:4|confirmed'
        ], [
            'password.required' => 'رمز عبور نمی‌تواند خالی باشد',
            'password.min' => 'رمز عبور نمی‌تواند کمتر از جهار کاراکتر باشد',
            'password.confirmed' => 'فیلدها با هم تطابق ندارند',
        ]);
        $user->update(['password' => bcrypt($request->password)]);

        Log::log('users',  "ویرایش رمز",'رمز کاربر' . $user->fullName() . ' توسط '.  auth()->user()->fullname()  .' با موفقیت به روز شد');


        session()->flash('success', 'رمز کاربر توسط '.  auth()->user()->fullName() .' با موفقیت به روز شد');

        return redirect('/users');
    }

    public function destroy(User $user)
    {
        $usr = $user;
        $this->authorizeForUser(auth()->user(), 'delete', $user);
        $user->reserves()->delete();
        $user->delete();

        Log::log('users', "حذف","حذف کاربر {$usr->fullName()}" . 'توسط' . auth()->user()->fullName() . " ( " . auth()->user()->employnumber . " ) " );


        session()->flash('delete', 'کاربر با موفقیت حذف شد');

        return redirect('/users');
    }

    public function editOwnPassword(User $user)
    {
        $this->authorizeForUser(auth()->user(), 'updatePassword', $user);

        return view('users.ownpasswordedit', compact('user'));

    }

    public function updateOwnPassword(Request $request, User $user)
    {

        $this->authorizeForUser(auth()->user(), 'updatePassword', $user);

        $this->validate($request, [
            'currentpassword' => 'required',
            'password' => 'required|confirmed'
        ],[
            'currentpassword.required' => 'وارد کردن رمز عبور فعلی الزامی است',
            'password.required' => 'وارد کردن فیلد رمز عبور الزامی‌ است',
            'password.confirmed' => 'فیلدهای وارد شده با هم تطابق ندارند'
        ]);


        if(auth()->attempt(['employnumber' => $user->employnumber, 'password' => $request->currentpassword])){

            if (!auth()->attempt(['employnumber' => $user->employnumber, 'password' => $request->password])){
                $user->update([
                    'password' => bcrypt($request->password)
                ]);

                Log::log('users', "ویرایش رمز  {$user->fullName()}", "رمز کاربر  {$user->fullName()}  توسط " . auth()->user()->fullName() . " ( " . auth()->user()->employnumber . " ) " . "تغغیر یافت");

                session()->flash('success', 'رمز شما با موفقیت به روز شد');

                return redirect('/home');
            } else {
                return back()->withErrors(['message' => 'رمز جدید نباید با رمز قبلی یکسان باشد']);
            }
        }else {
            return back()->withErrors(['message' => 'رمز قبلی صحیح وارد نشده است']);
        }
    }
}

resources/views/users/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن کاربر</h3>
                    @include('layouts.formrequiredfields')
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('users.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="firstname" class="text-danger"><small>*</small>نام</label>
                            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="نام" value="{{old('firstname')??''}}">
                        </div>
                        <div class="form-group">
                            <label for="lasttname" class="text-danger"><small>*</small>نام خانوادگی</label>
                            <input type="text" class="form-control" name="lasttname" id="lasttname" placeholder="نام خانوادگی" value="{{old('lasttname')??''}}">
                        </div>
                        <div class="form-group">
                            <label for="employnumber" class="text-danger"><small>*</small>شماره کارمندی</label>
                            <input type="number" class="form-control" name="employnumber" id="employnumber" placeholder="شماره کارمندی" value="{{old('employnumber')??''}}">
                        </div>
                        <div class="form-group">
                            <label for="phone" class="text-danger"><small>*</small>شماره موبایل</label>
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="شماره موبایل" value="{{old('phone')??''}}">
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-danger"><small>*</small>رمز عبور</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation" class="text-danger"><small>*</small> تکرار رمز عبور</label>
                            <input type="password" class="form-control" name="password_confirmation" id="password_confiramtion">
                        </div>
                        <div class="form-group">
                            <label for="role_id" class="text-danger"><small>*</small>نقش</label>
                            <select type="text" class="form-control" id="role_id" name="role_id" placeholder="عنوان نقش">
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}">{{$role->title}}</option>
                                @endforeach
                            </select>
                        </div>

                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"> ویرایش اطلاعات کاربر {{$user->fullName()}} </h3>
                    @include('layouts.formrequiredfields')
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('users.update', $user)}}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="firstname" class="text-danger"><small>*</small>نام</label>
                            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="نام" value="{{$user->firstname}}">
                        </div>
                        <div class="form-group">
                            <label for="lastname" class="text-danger"><small>*</small>نام خانوادگی</label>
                            <input type="text" class="form-control" name="lastname" id="lastname" placeholder="نام خانوادگی" value="{{$user->lastname}}">
                        </div>
                        <div class="form-group">
                            <label for="employnumber" class="text-danger"><small>*</small>شماره کارمندی</label>
                            <input type="number" class="form-control" name="employnumber" id="employnumber" value="{{$user->employnumber}}">
                        </div>
                        <div class="form-group">
                            <label for="phone" class="text-danger"><small>*</small>شماره موبایل</label>
                            <input type="text" class="form-control" name="phone" id="phone" value="{{$user->phone}}">
                        </div>

                        <div class="form-group">
                            <label for="role_id" class="text-danger"><small>*</small>نقش</label>
                            <select type="text" class="form-control" id="role_id" name="role_id" placeholder="عنوان نقش">
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}" @if($user->role_id == $role->id) selected @endif>{{$role->title}}</option>
                                @endforeach
                            </select>
                        </div>

                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">جدول کاربران</h3>
                    <a href="{{route('users.create')}}" class="btn btn-success">افزودن کاربر جدید</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">نام</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">شماره کارمندی</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">شماره موبایل</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">نقش کاربر</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(count($users) > 0)
                                        @foreach($users as $user)
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    <a href="{{route('users.show', $user)}}">{{$user->fullName()}}</a>
                                                </td>
                                                <td>{{$user->employnumber}}</td>
                                                <td>{{$user->phone}}</td>
                                                <td>{{$user->role->title}}</td>
                                                <td class="td-controls">
                                                    <a href="{{route('users.edit', $user)}}" class="btn btn-info">ویرایش</a>
                                                    <a href="/password/{{$user->id}}/edit" class="btn btn-warning">ویرایش رمز</a>
                                                    <form action="{{route('users.destroy', $user)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('آیا مطمئن هستید؟')" class="btn btn-danger">حذف</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                    <tfoot>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">نام</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">شماره کارمندی</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">شماره موبایل</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">نقش کاربر</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-sm-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                    {{$users->links()}}

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

@endsection

resources/views/users/ownpasswordedit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">ویرایش رمز عبور</h3>
                    @include('layouts.formrequiredfields')
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="/users/{{$user->id}}/updatepassword" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="currentpassword"class="text-danger"><small>*</small>رمز عبور فعلی</label>
                            <input type="password" class="form-control" name="currentpassword" id="currentpassword">
                        </div>

                        <div class="form-group">
                            <label for="password" class="text-danger"><small>*</small>رمز عبور جدید</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation" class="text-danger"><small>*</small> تکرار رمز عبور جدید</label>
                            <input type="password" class="form-control" name="password_confirmation" id="password_confiramtion">
                        </div>

                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">

                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>



                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/users/passwordedit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">ویرایش رمز عبور</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="/password/{{$user->id}}/update" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">

                        <div class="form-group">
                            <label for="password">رمز عبور جدید</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation"> تکرار رمز عبور جدید</label>
                            <input type="password" class="form-control" name="password_confirmation" id="password_confiramtion">
                        </div>

                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection