routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\AdminConfig;
use Carbon\Carbon;

Route::get('/', function () {
    return view('welcome');
});



Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::delete('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/foods', 'FoodController');

Route::resource('/users', 'UserController');

Route::resource('/roles', 'RoleController');

Route::resource('/accesses', 'AccessController');


Route::get('/reserves/create', 'ReserveController@create');
//Route::post('/reserves/{schedule}/store', 'ReserveController@store');
Route::post('/reserves', 'ReserveController@store');
Route::delete('/reserves/{reserve}/destroy', 'ReserveController@destroy');

//Route::get('/schedules', 'ScheduleFoodController@index');
Route::get('/schedules/create', 'ScheduleFoodController@create');
Route::post('/schedules/store', 'ScheduleFoodController@store');
Route::get('/schedules/shownextweek', 'ScheduleFoodController@showSchedulesReservedByUsers');


Route::delete('/schedules/{scheduleFood}/reserve/destroy', 'ScheduleFoodController@deleteReservations');


Route::get('/roles/{role}/permissions', 'PermissionRoleController@create');
Route::post('/roles/{role}/permissions/store', 'PermissionRoleController@store');
Route::delete('/permissionroles/{permissionrole}/destroy', 'PermissionRoleController@destroy');

Route::get('/password/{user}/edit', 'UserController@passwordEdit');
Route::patch('/password/{user}/update', 'UserController@passwordUpdate');

Route::get('/users/{user}/editpassword', 'UserController@editOwnPassword');
Route::patch('/users/{user}/updatepassword', 'UserController@updateOwnPassword');

Route::get('/print', 'ScheduleFoodController@print');

Route::resource('/configs', 'AdminConfigController');


Route::get('/logs', 'LogController@index');


Route::delete('/schedules/{schedule}/users/{user}', 'ScheduleFoodController@deleteUserReserve');

app/Food.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Food extends Model
{
    protected $guarded=[];

    public function schedules()
    {
        return $this->hasMany(ScheduleFood::class, 'food_id');
    }

}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use App\Food;
use App\Http\Requests\FoodRequest;
use App\Http\Requests\FoodPolicy;
use App\Log;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $this->authorizeForUser(auth()->user(), 'viewAny', \App\Food::class);
        $foods = Food::paginate(10);
        return view('foods.index', compact('foods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', [\App\Food::class, auth()->user()]);
        return view('foods.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FoodRequest $request)
    {

        $this->authorize('create', [\App\Food::class, auth()->user()]);

        $imageurl = "";
        if(request('image')){
            $imageurl = str_replace('public', '/storage',Storage::putFile('/public/posts',request('image')));
        }

        $food = Food::create([
            'name' => request('name'),
            'description' => request('description'),
            'cost' => request('cost'),
            'image' => $imageurl
        ]);

        Log::log('foods', "ایجاد", $food->name  . " توسط کاربر " . auth()->user()->fullName() . " ( " . auth()->user()->employnumber . " ) " . " ایجاد شد. ");


        session()->flash("success", "{$food->name} با موفقیت اضافه شد ");

        return redirect("/foods");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Food  $food
     * @return \Illuminate\Http\Response
     */
    public function show(Food $food)
    {
        $this->authorizeForUser(auth()->user(), 'view', $food);
        return view('foods.show', compact('food'));
    }


    public function edit(Food $food)
    {
        $this->authorizeForUser(auth()->user(), 'update', $food);
        return view('foods.edit', compact('food'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Food  $food
     * @return \Illuminate\Http\Response
     */
    public function update(FoodRequest $request, Food $food)
    {
        $fd = $food;
        $this->authorizeForUser(auth()->user(), 'update', $food);
        $food->update($request->all());

        Log::log('foods', "ویرایش ", " غذای " . $food->name . " توسط کاربر " . auth()->user()->fullName() . " ( " . auth()->user()->employnumber . " ) " . " تغییر یافت ");


        session()->flash("success", "{$food->name} با موفقیت ویرایش شد ");
        return redirect("/foods");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Food  $food
     * @return \Illuminate\Http\Response
     */
    public function destroy(Food $food)
    {
        $fd = $food;
        $this->authorizeForUser(auth()->user(), 'delete', $food);
        if(!empty($food->schedules()) && $food->schedules->count() > 0){
            session()->flash('danger', 'امکان حذف غذا وجود ندارد');
            return back();
        } else {
            $food->delete();

            Log::log('foods', "حذف", " غذای " . $fd->name . " توسط کاربر " . auth()->user()->fullName() . " ( " . auth()->user()->employnumber . " ) " . " حذف شد. ");

            session()->flash('delete', "با موفقیت حذف شد");
        }
        return redirect("/foods");
    }
}

resources/views/foods/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن غذای جدید</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('foods.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name" class="text-danger"><small>*</small>عنوان غذا</label>
                            <input type="name" class="form-control" id="name" name="name" placeholder="عنوان غذا" value="{{old('name')??''}}">
                        </div>
                        <div class="form-group">
                            <label for="cost" class="text-danger"><small>*</small>هزینه</label>
                            <input type="text" class="form-control" id="cost" name="cost" placeholder="هزینه" value="7000">
                        </div>
                        <div class="form-group">
                            <label for="image">ارسال تصویر</label>
                            <input type="file" id="image" name="image" value="تصویر">

                        </div>

                    </div>
                    <div class="form-group">
                        <label for="description" class="text-danger"><small>*</small> توضیحات</label>
                        <textarea id="description" name="description" class="form-control" rows="3" placeholder="توضیحات"></textarea>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/foods/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن غذای جدید</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('foods.update', $food)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name" class="text-danger"><small>*</small>عنوان غذا</label>
                            <input type="name" class="form-control" id="name" name="name" value="{{$food->name}}">
                        </div>
                        <div class="form-group">
                            <label for="cost" class="text-danger"><small>*</small>هزینه</label>
                            <input type="text" class="form-control" id="cost" name="cost" placeholder="هزینه" value="{{$food->cost}}">
                        </div>
                        <div class="form-group">
                            <label for="image">ارسال تصویر</label>
                            <input type="file" id="image" name="image" value="تصویر">

                        </div>

                    </div>
                    <div class="form-group">
                        <label for="description" class="text-danger"><small>*</small> توضیحات</label>
                        <textarea id="description" name="description" class="form-control" rows="3" placeholder="توضیحات">{{$food->description}}
                        </textarea>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/foods/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">جدول غذا ها</h3>
                    <a href="{{route('foods.create')}}" class="btn btn-success">افزودن غذای جدید</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">تصویر</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">عنوان</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">هزینه</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">توضیحات</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if($foods->count() > 0)
                                @foreach($foods as $food)
                                    <tr role="row" class="odd">
                                        <td class="sorting_1"><img width="100" height="100" src="{{$food->image}}" alt=""></td>
                                        <td><a href="{{route('foods.show', $food)}}">{{$food->name}}</a></td>
                                        <td>{{$food->cost}}</td>
                                        <td>{{$food->description}}</td>
                                        <td class="td-controls">
                                            <a href="{{route('foods.edit', $food)}}" class="btn btn-info">ویرایش</a>
                                            <form action="{{route('foods.destroy', $food)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('آیا مطمئن هستید؟')" class="btn btn-danger">حذف</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif

                        </tbody>
                        <tfoot>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">تصویر</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">عنوان</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">هزینه</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">توضیحات</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
                <div class="row">
                    <div class="col-sm-7">
                        <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                            {{$foods->links()}}
                        </div>
                    </div>
                </div>
            </div>
            </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

@endsection

resources/views/foods/show.blade.php
@extends('layouts.main')

@section('content')
    hi
@endsection