routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\AdminConfig;
use Carbon\Carbon;

Route::get('/', function () {
    return view('welcome');
});



Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::delete('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/foods', 'FoodController');

Route::resource('/users', 'UserController');

Route::resource('/roles', 'RoleController');

Route::resource('/accesses', 'AccessController');


Route::get('/reserves/create', 'ReserveController@create');
//Route::post('/reserves/{schedule}/store', 'ReserveController@store');
Route::post('/reserves', 'ReserveController@store');
Route::delete('/reserves/{reserve}/destroy', 'ReserveController@destroy');

//Route::get('/schedules', 'ScheduleFoodController@index');
Route::get('/schedules/create', 'ScheduleFoodController@create');
Route::post('/schedules/store', 'ScheduleFoodController@store');
Route::get('/schedules/shownextweek', 'ScheduleFoodController@showSchedulesReservedByUsers');


Route::delete('/schedules/{scheduleFood}/reserve/destroy', 'ScheduleFoodController@deleteReservations');


Route::get('/roles/{role}/permissions', 'PermissionRoleController@create');
Route::post('/roles/{role}/permissions/store', 'PermissionRoleController@store');
Route::delete('/permissionroles/{permissionrole}/destroy', 'PermissionRoleController@destroy');

Route::get('/password/{user}/edit', 'UserController@passwordEdit');
Route::patch('/password/{user}/update', 'UserController@passwordUpdate');

Route::get('/users/{user}/editpassword', 'UserController@editOwnPassword');
Route::patch('/users/{user}/updatepassword', 'UserController@updateOwnPassword');

Route::get('/print', 'ScheduleFoodController@print');

Route::resource('/configs', 'AdminConfigController');


Route::get('/logs', 'LogController@index');


Route::delete('/schedules/{schedule}/users/{user}', 'ScheduleFoodController@deleteUserReserve');

resources/views/configs/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن پیکربندی جدید</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('configs.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="day">روز</label>
                            <select name="day" id="day" class="form-control">
                                <option value="1">شنبه</option>
                                <option value="2">یک شنبه</option>
                                <option value="3">دو شنبه</option>
                                <option value="4">سه شنبه</option>
                                <option value="5">جهار شنبه</option>
                                <option value="6">پنج شنبه</option>
                                <option value="0">جمعه</option>
                            </select>
                        </div>
                    </div>

                    <div class="box-body">
                        <div class="bootstrap-timepicker">
                            <div class="form-group">
                                <label>انتخاب زمان</label>

                                <div class="input-group">
                                    <input type="text" class="form-control timepicker" name="time" id="time">

                                    <div class="input-group-addon">
                                        <i class="fa fa-clock-o"></i>
                                    </div>
                                </div>
                                <!-- /.input group -->
                            </div>
                            <!-- /.form group -->
                        </div>
                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/configs/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">ویرایش پیکربندی</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
{{--                @php--}}
{{--                    dd($adminConfig);--}}
{{--                @endphp--}}
                <form role="form" action="{{route('configs.update', $config)}}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="day">روز</label>
                            <select name="day" id="day" class="form-control">
                                <option value="1" @if($config->day == 1) selected @endif>شنبه</option>
                                <option value="2" @if($config->day == 2) selected @endif>یک شنبه</option>
                                <option value="3" @if($config->day == 3) selected @endif>دو شنبه</option>
                                <option value="4" @if($config->day == 4) selected @endif>سه شنبه</option>
                                <option value="5" @if($config->day == 5) selected @endif>جهار شنبه</option>
                                <option value="6" @if($config->day == 6) selected @endif>پنج شنبه</option>
                                <option value="0" @if($config->day == 0) selected @endif>جمعه</option>
                            </select>
                        </div>
                    </div>

                    <div class="box-body">
                        <div class="bootstrap-timepicker">
                            <div class="form-group">
                                <label>انتخاب زمان</label>

                                <div class="input-group">
                                    <input type="text" class="form-control timepicker" name="time" id="time">

                                    <div class="input-group-addon">
                                        <i class="fa fa-clock-o"></i>
                                    </div>
                                </div>
                                <!-- /.input group -->
                            </div>
                            <!-- /.form group -->
                        </div>
                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/configs/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">جدول پیکر بندی ها</h3>
                    @can('create', [ \App\AdminConfig::class, auth()->user()])
                        <a href="{{route('configs.create')}}" class="btn btn-success">افزودن پیکر بندی جدید</a>
                    @endcan
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">روز</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">ساعت</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if($configs->count() > 0)
                                        @foreach($configs as $config)
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{$config->dayname()}}</td>
                                                <td>
                                                    {{$config->time}}
                                                </td>
                                                <td class="td-controls">
                                                    <a href="{{route('configs.edit', $config)}}" class="btn btn-info">ویرایش</a>
                                                    <form action="{{route('configs.destroy', $config)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('آیا مطمئن هستید؟')" class="btn btn-danger">حذف</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                    <tfoot>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">تصویر</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">دسترسی ها</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

@endsection