routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\AdminConfig;
use Carbon\Carbon;

Route::get('/', function () {
    return view('welcome');
});



Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::delete('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/foods', 'FoodController');

Route::resource('/users', 'UserController');

Route::resource('/roles', 'RoleController');

Route::resource('/accesses', 'AccessController');


Route::get('/reserves/create', 'ReserveController@create');
//Route::post('/reserves/{schedule}/store', 'ReserveController@store');
Route::post('/reserves', 'ReserveController@store');
Route::delete('/reserves/{reserve}/destroy', 'ReserveController@destroy');

//Route::get('/schedules', 'ScheduleFoodController@index');
Route::get('/schedules/create', 'ScheduleFoodController@create');
Route::post('/schedules/store', 'ScheduleFoodController@store');
Route::get('/schedules/shownextweek', 'ScheduleFoodController@showSchedulesReservedByUsers');


Route::delete('/schedules/{scheduleFood}/reserve/destroy', 'ScheduleFoodController@deleteReservations');


Route::get('/roles/{role}/permissions', 'PermissionRoleController@create');
Route::post('/roles/{role}/permissions/store', 'PermissionRoleController@store');
Route::delete('/permissionroles/{permissionrole}/destroy', 'PermissionRoleController@destroy');

Route::get('/password/{user}/edit', 'UserController@passwordEdit');
Route::patch('/password/{user}/update', 'UserController@passwordUpdate');

Route::get('/users/{user}/editpassword', 'UserController@editOwnPassword');
Route::patch('/users/{user}/updatepassword', 'UserController@updateOwnPassword');

Route::get('/print', 'ScheduleFoodController@print');

Route::resource('/configs', 'AdminConfigController');


Route::get('/logs', 'LogController@index');


Route::delete('/schedules/{schedule}/users/{user}', 'ScheduleFoodController@deleteUserReserve');

app/Http/Controllers/AccessController.php
<?php

namespace App\Http\Controllers;

use App\Access;
use App\Helper\Helper;
use App\Http\Requests\AccessRequest;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AccessController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorizeForUser(auth()->user(), 'viewAny', \App\Access::class);
        $accesses = Access::all();
        return view('accesses.index', compact('accesses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorizeForUser(auth()->user(), 'create', \App\Access::class);
        $roles = Role::all();
        $tables = Helper::dbTables();
        return view('accesses.create', compact('roles', 'tables'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AccessRequest $request)
    {
        $this->authorizeForUser(auth()->user(), 'create', \App\Access::class);

        $access = Access::create([
            'role_id' => $request->role_id,
            'table_name' => $request->table_name,
            'create' => (boolean)$request->create,
            'read' => (boolean)$request->read,
            'update' => (boolean)$request->update,
            'delete' => (boolean)$request->delete
        ]);

        session()->flash('success', 'دسترسی جدید با موفقیت ایجاد شد');

        return redirect(route('accesses.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Access  $access
     * @return \Illuminate\Http\Response
     */
    public function show(Access $access)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Access  $access
     * @return \Illuminate\Http\Response
     */
    public function edit(Access $access)
    {
        $this->authorizeForUser(auth()->user(), 'update', $access);
        $roles = Role::all();
        $tables = Helper::dbTables();
        return view('accesses.edit', compact('access', 'roles', 'tables'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Access  $access
     * @return \Illuminate\Http\Response
     */
    public function update(AccessRequest $request, Access $access)
    {
        $this->authorizeForUser(auth()->user(), 'update', $access);

        $access->update([
            'role_id' => $request->role_id,
            'table_name' => $request->table_name,
            'create' => (boolean)$request->create,
            'read' => (boolean)$request->read,
            'update' => (boolean)$request->update,
            'delete' => (boolean)$request->delete,
        ]);
        session()->flash('success', 'دسترسی با موفقیت ویرایش شد.');
        return redirect(route('accesses.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Access  $access
     * @return \Illuminate\Http\Response
     */
    public function destroy(Access $access)
    {
        $this->authorizeForUser(auth()->user(), 'delete', $access);
        $access->delete();

        return redirect(route('accesses.index'));

    }
}

resources/views/accesses/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">مدیریت دسترسی نقش</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('accesses.store')}}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="role_id">عنوان نقش</label>
                            <select type="text" class="form-control" id="role_id" name="role_id" placeholder="عنوان نقش">
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}">{{$role->title}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="table_name">نام جدول</label>
                            <select name="table_name" id="table_name" class="form-control">
                                <option value="" disabled selected>انتخاب جدول</option>
                                @foreach($tables as $table)
                                    <option value="{{$table}}">{{$table}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="create">
                                    قابلیت ایجاد
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="read">
                                    قابلیت خواندن
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="update">
                                    قابلیت ویرایش
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="delete">
                                    قابلیت حذف
                                </label>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/accesses/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">مدیریت دسترسی نقش</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{route('accesses.update', $access)}}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="role_id">عنوان نقش</label>
                            <select type="text" class="form-control" id="role_id" name="role_id" placeholder="عنوان نقش">
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}" @if($role->id == $access->role_id) selected @endif>{{$role->title}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="table_name">نام جدول</label>
                            <select name="table_name" id="table_name" class="form-control">
                                <option value="" disabled>انتخاب جدول</option>
                                @foreach($tables as $table)
                                    <option value="{{$table}}" @if($table == $access->table_name) selected @endif>{{$table}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="create" @if($access->create) checked @endif>
                                    قابلیت ایجاد
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="read" @if($access->read) checked @endif>
                                    قابلیت خواندن
                                </label>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="update" @if($access->update) checked @endif>
                                    قابلیت ویرایش
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="delete" @if($access->delete) checked @endif>
                                    قابلیت حذف
                                </label>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </form>

                @if($errors->count() > 0)
                    <div class="form-group has-error">
                        @foreach($errors->all() as $error)
                            <span class="help-block">{{$error}}</span>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/accesses/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">جدول دسترسی‌ ها</h3>
                    <a href="{{route('accesses.create')}}" class="btn btn-success btn-lg">افزودن دسترسی جدید</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">عنوان</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">جدول</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">ایجاد</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">خوندن</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">ویرایش</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">حذف</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if($accesses->count() > 0)
                                        @foreach($accesses as $access)
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{$access->role->title}}</td>
                                                <td>{{$access->table_name}}</td>
                                                @if($access->create)
                                                    <td>بله</td>
                                                @else
                                                    <td>خیر</td>
                                                @endif
                                                @if($access->read)
                                                    <td>بله</td>
                                                @else
                                                    <td>خیر</td>
                                                @endif
                                                @if($access->update)
                                                    <td>بله</td>
                                                @else
                                                    <td>خیر</td>
                                                @endif
                                                @if($access->delete)
                                                    <td>بله</td>
                                                @else
                                                    <td>خیر</td>
                                                @endif

                                                {{--                                                <td></td>--}}
                                                <td style="display: inline-flex; flex-direction: row; align-items: center;">
                                                    <a href="{{route('accesses.edit', $access)}}" class="btn btn-info btn-lg">ویرایش</a>
                                                    <form action="{{route('accesses.destroy', $access)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger btn-lg">حذف</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                    <tfoot>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">عنوان</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">جدول</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">ایجاد</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">خوندن</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">ویرایش</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">حذف</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">کنترل ها</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-5">
                                <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div>
                            <div class="col-sm-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

@endsection